# Generated by Django 3.2 on 2021-04-21 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batting_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.battingstyle'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bowling_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bowlingstyle'),
        ),
    ]
