# Generated by Django 3.2 on 2021-04-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210421_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bowlingprofile',
            name='player',
        ),
        migrations.AddField(
            model_name='profile',
            name='balls',
            field=models.PositiveIntegerField(default=0, verbose_name='not out'),
        ),
        migrations.AddField(
            model_name='profile',
            name='batting_innings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='bowling_innings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='hs',
            field=models.PositiveIntegerField(default=0, verbose_name='highest score'),
        ),
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no',
            field=models.PositiveIntegerField(default=0, verbose_name='not out'),
        ),
        migrations.AddField(
            model_name='profile',
            name='runs',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wkts',
            field=models.PositiveIntegerField(default=0, verbose_name='wickets'),
        ),
        migrations.DeleteModel(
            name='BattingProfile',
        ),
        migrations.DeleteModel(
            name='BowlingProfile',
        ),
    ]
