# Generated by Django 3.2 on 2021-04-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210421_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_4',
            field=models.PositiveIntegerField(default=0, verbose_name='4s'),
        ),
        migrations.AddField(
            model_name='profile',
            name='_6',
            field=models.PositiveIntegerField(default=0, verbose_name='6s'),
        ),
    ]
