# Generated by Django 3.2 on 2021-04-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210421_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='runs',
            new_name='batting_runs',
        ),
        migrations.AddField(
            model_name='profile',
            name='bowling_runs',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balls',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
