# Generated by Django 3.2 on 2021-04-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210421_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='_4',
            new_name='fours',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_6',
            new_name='sixes',
        ),
    ]
