# Generated by Django 3.2 on 2021-04-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210423_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fifties',
            field=models.PositiveIntegerField(default=0, verbose_name='50s'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hundreds',
            field=models.PositiveIntegerField(default=0, verbose_name='100s'),
        ),
    ]
