# Generated by Django 3.2 on 2021-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210423_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='catches',
            field=models.PositiveIntegerField(default=0, verbose_name='Ct'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stumped',
            field=models.PositiveIntegerField(default=0, verbose_name='St'),
        ),
    ]
