# Generated by Django 3.2 on 2021-04-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210423_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_keeper',
            field=models.BooleanField(default=False),
        ),
    ]
