# Generated by Django 3.2 on 2021-04-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210423_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_captain',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_keeper',
        ),
    ]
