# Generated by Django 3.2 on 2021-05-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210501_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='batting_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bowling_runs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
