# Generated by Django 3.2 on 2021-05-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210501_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.URLField(blank=True),
        ),
    ]
