# Generated by Django 3.2 on 2021-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.URLField(blank=True, default='https://drive.google.com/file/d/1W50JnkJ0V1U0grarMPozNhj-VTxMexTA/preview'),
        ),
    ]
