# Generated by Django 3.2 on 2021-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_pic',
            field=models.URLField(default='https://drive.google.com/file/d/1W50JnkJ0V1U0grarMPozNhj-VTxMexTA/preview', editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.URLField(blank=True),
        ),
    ]
