# Generated by Django 3.2 on 2021-05-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210509_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_pic',
            field=models.URLField(default='https://s.ndtvimg.com/images/entities/300/jos-buttler-1367.png', editable=False),
        ),
    ]
