# Generated by Django 3.2 on 2021-05-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_default_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_pic',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.URLField(default='https://s.ndtvimg.com/images/entities/300/jos-buttler-1367.png'),
        ),
    ]
