# Generated by Django 3.2 on 2021-05-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210528_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_pic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.CharField(blank=True, default='https://s.ndtvimg.com/images/entities/300/jos-buttler-1367.png', max_length=256),
        ),
    ]
