# Generated by Django 3.2 on 2021-05-02 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
